### ISSUE TITLE
Dict generation no more working  following PyGlossary 4.3.0 upgrade

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1155]
PyGlossary was upgraded to 4.3.0 in #1154. Since then the GitHub action to update dictionnaries does not work anymore:

```shell
$ pyglossary --ui=none data/no/dict-no.df dict-data.ifo
```

```python
[INFO] Automatically switching to SQLite mode for writing Stardict
[CRITICAL] Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/bin/pyglossary", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/ui/main.py", line 724, in main
    sys.exit(0 if base_ui_run(**runKeywordArgs) else 1)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/ui/main.py", line 191, in base_ui_run
    glos.convert(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/glossary.py", line 1383, in convert
    sort, direct = self._resolveConvertSortParams(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/glossary.py", line 1323, in _resolveConvertSortParams
    if self._switchToSQLite(inputFilename, outputFormat, writeOptions):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/glossary.py", line 1276, in _switchToSQLite
    self._data = SqList(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/sqlist.py", line 38, in __init__
    self._con = connect(filename)
sqlite3.OperationalError: unable to open database file

Exception ignored in: <function SqList.__del__ at 0x7f30ae36c820>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/sqlist.py", line 155, in __del__
    self.close()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyglossary/sqlist.py", line 146, in close
    if self._con is None:
AttributeError: 'SqList' object has no attribute '_con'
```

**Comment by BoboTiG** [comment]
Looking at the [changes](https://github.com/ilius/pyglossary/releases/tag/4.3.0), we could try to use the `--no-sqlite` argument.

**Comment by BoboTiG** [comment]
We need to add a simple test to cover such changes. The PyGlossary part is not covered in our unit tests.

**Comment by ilius** [comment]
Is the exception fixed after `4.4.0`?

**Comment by BoboTiG** [comment]
Let me trigger the job, we will see in a couple of minutes :)

**Comment by BoboTiG** [comment]
The overall behavior remains the same:
```python
[INFO] Automatically switching to SQLite mode for writing Stardict
[INFO] Using sortKeyName = 'stardict'
[CRITICAL] Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/bin/pyglossary", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pyglossary/ui/main.py", line 748, in main
    sys.exit(0 if base_ui_run(**runKeywordArgs) else 1)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pyglossary/ui/main.py", line 192, in base_ui_run
    glos.convert(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pyglossary/glossary.py", line 1461, in convert
    direct, sort, namedSortKey = self._resolveConvertSortParams(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pyglossary/glossary.py", line 1387, in _resolveConvertSortParams
    self._switchToSQLite(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pyglossary/glossary.py", line 1280, in _switchToSQLite
    self._data = SqEntryList(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pyglossary/sq_entry_list.py", line 60, in __init__
    self._con = connect(filename)
sqlite3.OperationalError: unable to open database file

[ERROR] 'SqEntryList' object has no attribute '_con'
```

**Comment by BoboTiG** [comment]
If you would like to give a hand, I opened the #1157 PR. I might be calling PyGlossary with wrong arguments :thinking:

**Comment by ilius** [comment]
SQLite file is created in `~/.cache/pyglossary/` directory, which is not automatically updated. And hence the exception.
I will create a release `4.4.1` to create the directory automatically.

But you may also use `--no-sqlite`, specially if your file is not big.

**Comment by BoboTiG** [comment]
Thanks for your implication and help @ilius, greatly appreciated :muscle: :)

**Comment by ilius** [comment]
No worries.

**Comment by BoboTiG** [comment]
@ilius since I merged the patch, dict conversion are taking hours (with and without SQLite mode). {Example](https://github.com/BoboTiG/ebook-reader-dict/runs/4965749620?check_suite_focus=true).

Do you have an idea why?  It seems related to large dictionnaries, but the situation should not be different from when we called PyGlossary from the CLI :thinking:

**Comment by ilius** [comment]
Yes, it should not be different from CLI.

But if you have large glossaries, you should switch to `4.4.1` and enable SQLite mode.
Otherwise you gotta make sure you don't run out of RAM on ci.
SQLite mode even reduces running time in my experience for large glossaries.

**Comment by ilius** [comment]
Yes it should not be different from CLI.
But if you have large dictionaries, you should definitely switch `4.4.1 and re-enable sqlite mode.
Otherwise you have to make sure you don't run out of

**Comment by BoboTiG** [comment]
I found the issue: calls to `gc.collect()` when reading, and writing, files are killing performances when run from Python.

**Comment by BoboTiG** [comment]
I'll simply disable GC fr my use case :+1:

**Comment by ilius** [comment]
@BoboTiG Thanks for letting me know.
I will add a config and flag to disable the GC.

**Comment by ilius** [comment]
Looks like it's not even needed in Python 3.9.
I remember it was very different in Python 3.7 (it was not freeing entry objects without `gc.collect()`)
I don't know what's changed yet.

**Comment by ilius** [comment]
Also tested on Python 3.8 and doesn't make much difference.
So I removed `gc.collect()`
https://github.com/ilius/pyglossary/commit/8a09e5c452c23ced19c562b3697a337d81125dd6

**Comment by BoboTiG** [comment]
Wow that's cool! I'll revert 9d2aa0d2d72422fcabe9d9dd7e4dff7b58449ab9 when the new version will be out.
