### ISSUE TITLE
Fix several script failures

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1236]
[job](https://github.com/BoboTiG/ebook-reader-dict/runs/5429636088?check_suite_focus=true):

```python
Traceback (most recent call last):
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/es-campos-semanticos.py", line 62, in <module>
    next_page_url = process_cs_page(next_page_url, results)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/es-campos-semanticos.py", line 50, in process_cs_page
    template_text = template_text_div.find("p").text.strip()
AttributeError: 'NoneType' object has no attribute 'find'
Exception in thread Thread-10 (process_script):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/__main__.py", line 45, in process_script
    data = subprocess.check_output(["python", f"scripts/{script}"], text=True)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'scripts/es-campos-semanticos.py']' returned non-zero exit status 1.
```

```python
Traceback (most recent call last):
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/de-langs.py", line 54, in <module>
    next_page_url = process_page(next_page_url, languages)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/de-langs.py", line 34, in process_page
    content = sub_soup.find("div", {"class": "mw-parser-output"}).find(
AttributeError: 'NoneType' object has no attribute 'find'
Exception in thread Thread-4 (process_script):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/__main__.py", line 45, in process_script
    data = subprocess.check_output(["python", f"scripts/{script}"], text=True)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'scripts/de-langs.py']' returned non-zero exit status 1.
```

```python
Traceback (most recent call last):
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/en-labels.py", line 169, in <module>
    results |= process_page(page_url, repl, stop_line, var_name, print_result=False)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/en-labels.py", line 31, in process_page
    text = div.text
AttributeError: 'NoneType' object has no attribute 'text'
Exception in thread Thread-7 (process_script):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/__main__.py", line 45, in process_script
    data = subprocess.check_output(["python", f"scripts/{script}"], text=True)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'scripts/en-labels.py']' returned non-zero exit status 1.
```

```python
Traceback (most recent call last):
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/en-langs.py", line 101, in <module>
    m = process_lang_page(url)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/en-langs.py", line 74, in process_lang_page
    lines = get_content(url)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/en-langs.py", line 67, in get_content
    content_div = content_div.findChild(
AttributeError: 'NoneType' object has no attribute 'findChild'
Exception in thread Thread-8 (process_script):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/scripts/__main__.py", line 45, in process_script
    data = subprocess.check_output(["python", f"scripts/{script}"], text=True)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'scripts/en-langs.py']' returned non-zero exit status 1.
```

**Comment by lasconic** [comment]
I can't reproduce the crash on `scripts/es-campos-semanticos.py` and the other errors look similar. Could it be that we are blacklisted by WP ?

**Comment by lasconic** [comment]
One way to find out would be to move `get_url_content` out from `check_word.py` and in `utils.py` but then I have no idea how to use code from wikidict in scripts...

**Comment by lasconic** [comment]
In the above PR, I factorized the network calls into scripts_utils.py and added retries and timeouts. Let's see if it works better.

**Comment by BoboTiG** [comment]
It seems better 👍
