### ISSUE TITLE
Update workflow is broken

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1337]
The update workflow failed 6 times out of 8.

The first failure: https://github.com/BoboTiG/ebook-reader-dict/actions/runs/2687401499

The last one gives so much zero details:

```bash
$ python -Wd -m wikidict fr --render
>>> Loading data/fr/data_wikicode-20220720.json ...
>>> Loaded 1,897,068 words from data/fr/data_wikicode-20220720.json
 !! Missing 'Lang-ar' template support for word 'Adonis'
 !! Missing 'ar-cf' template support for word 'Ali'
 !! Missing 'ar-cf' template support for word 'alcade'
/home/runner/work/_temp/9b7d5e05-a736-4586-86f5-9c97da6d3c1f.sh: line 1:  6642 Killed
```

Locally, it works like a charm.

**Comment by BoboTiG** [comment]
The code diff seems pretty harmless: https://github.com/BoboTiG/ebook-reader-dict/compare/a875a2f4be85bc90ed8509b1b4b07e686e69d76b..7e9e76dd09027a667d9bd0ce4a245b203dfb639c

Maybe should we check on potential GitHub runners changes.

**Comment by lasconic** [comment]
I see 
```
>>> Processing data/fr/pages-20220701.xml ...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/runpy.py", line [8](https://github.com/BoboTiG/ebook-reader-dict/runs/7381255002?check_suite_focus=true#step:8:9)6, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/wikidict/__main__.py", line 127, in <module>
    sys.exit(main())
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/wikidict/__main__.py", line 62, in main
    return parse.main(args["LOCALE"])
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/wikidict/parse.py", line 103, in main
    words = process(file, locale)
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/wikidict/parse.py", line 6[9](https://github.com/BoboTiG/ebook-reader-dict/runs/7381255002?check_suite_focus=true#step:8:10), in process
    for element in xml_iter_parse(file):
  File "/home/runner/work/ebook-reader-dict/ebook-reader-dict/wikidict/parse.py", line 22, in xml_iter_parse
    for event, element in doc:
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/BoboTiG/ebook-reader-dict/runs/7381255002?check_suite_focus=true#step:8:11).5/x64/lib/python3.10/xml/etree/ElementTree.py", line [12](https://github.com/BoboTiG/ebook-reader-dict/runs/7381255002?check_suite_focus=true#step:8:13)61, in iterator
    root = pullparser._close_and_return_root()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/xml/etree/ElementTree.py", line [13](https://github.com/BoboTiG/ebook-reader-dict/runs/7381255002?check_suite_focus=true#step:8:14)04, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: unclosed token: line 695613[20](https://github.com/BoboTiG/ebook-reader-dict/runs/7381255002?check_suite_focus=true#step:8:21), column 6
```

**Comment by lasconic** [comment]
Ok now I wonder if it will run.

**Comment by BoboTiG** [comment]
It seems so: https://github.com/BoboTiG/ebook-reader-dict/actions/runs/2829148853 :)

**Comment by lasconic** [comment]
Let's close this issue then !
