### ISSUE TITLE
[PT] Error with 'prenome'

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1340]
- Wiktionary page: https://pt.wiktionary.org/wiki/prenome

```bash
$ python -m wikidict pt --get-word prenome
```

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 127, in <module>
    sys.exit(main())
  File "__main__.py", line 98, in main
    return get_word.main(args["LOCALE"], args["--get-word"], raw=args["--raw"])
  File "get_word.py", line 82, in main
    get_and_parse_word(word, locale, raw)
  File "get_word.py", line 38, in get_and_parse_word
    details = get_word(word, locale)
  File "get_word.py", line 17, in get_word
    return parse_word(word, code, locale, force=True)
  File "render.py", line 352, in parse_word
    etymology = find_etymology(word, locale, etyl_data[0])
  File "render.py", line 186, in find_etymology
    definitions.append(process_templates(word, clean(etyl), locale))
  File "utils.py", line 453, in process_templates
    text = text.replace(tpl, transform(word, tpl[2:-2], locale))
  File "utils.py", line 613, in transform
    return str(transform_apply(word, tpl, tuple(parts), locale))
  File "/.../python3.10/site-packages/cachetools/__init__.py", line 641, in wrapper
    v = func(*args, **kwargs)
  File "utils.py", line 629, in transform_apply
    return str(last_template_handler[locale](parts, locale, word=word))
  File "lang/pt/__init__.py", line 253, in last_template_handler
    return langs[parts[0]]
KeyError: 'ine-pro'
```

**Comment by lasconic** [comment]
It seems our update script for pt-langs doesn't catch all the possible languages for the etm template :). Let's see.

**Comment by lasconic** [comment]
To be right we would need to get the languages from 
 - https://pt.wiktionary.org/w/index.php?title=Predefini%C3%A7%C3%A3o:nome_l%C3%ADngua&action=edit
and from
 - https://pt.wiktionary.org/wiki/Categoria:!Predefini%C3%A7%C3%A3o_ISO_639

**Comment by lasconic** [comment]
I'm not even sure wiktionary would let us do that. It needs to hit more than 1400 pages... We could extract it from a dump instead, or go the easy route and add the missing language at the end of pt/langs.py like we did previously...

**Comment by BoboTiG** [comment]
1,400 pages ... Yeah, let's go with the lazy approach 👍
