### ISSUE TITLE
[EN] Fix en-labels script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1510]
Just happened on the CI:

```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 103, in <module>
    process_page(url, repl, stop_line, var_name)
  File "scripts/en-labels.py", line 53, in process_page
    exec(code, globals())
  File "<string>", line 3
    function alias(a, b) for _, v in ipairs(b) do labels[v] = a   # allows aliases to be entered as a list
             ^^^^^
SyntaxError: invalid syntax
```

**Comment by BoboTiG** [comment]
Cf https://github.com/BoboTiG/ebook-reader-dict/actions/runs/3897834966/jobs/6655920248

**Comment by lasconic** [comment]
The conversion of the lua function is very fragile :)
