### ISSUE TITLE
[EN] Fix en-labels.py script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2002]
```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 238, in <module>
    results |= process_page(page_url, repl, stop_line, var_name, print_result=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/en-labels.py", line 100, in process_page
    exec(code, globals())
  File "<string>", line 9
    for i = 1, #data.labels - 1 do
    ^^^
SyntaxError: invalid syntax
```

**Comment by lasconic** [comment]
Should be fixed by https://github.com/BoboTiG/ebook-reader-dict/pull/2061
