### ISSUE TITLE
[EN] Fix en-labels script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2086]
```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 264, in <module>
    results |= process_page(page_url, repl, stop_line, var_name, print_result=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/en-labels.py", line 102, in process_page
    exec(code, globals())
  File "<string>", line 188
    }labels["Zhilen-Mzghem"] = {
     ^^^^^^
SyntaxError: invalid syntax
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/ebook-reader-dict/issues/2086">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/2086/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/2086/pledge.svg">
</picture>
</a>

**Comment by BoboTiG** [comment]
Fixed at the root: https://en.wiktionary.org/w/index.php?title=Module:labels/data/lang/lzz&diff=prev&oldid=80982668

**Comment by BoboTiG** [comment]
Another issue I missed yesterday:

```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 264, in <module>
    results |= process_page(page_url, repl, stop_line, var_name, print_result=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/en-labels.py", line 102, in process_page
    exec(code, globals())
  File "<string>", line 14
    from = "La Ribera"
    ^^^^
SyntaxError: invalid syntax
```

I am working on a fix right now.
