### ISSUE TITLE
[EN] Fix  "en-labels.py" script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2119]
```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 249, in <module>
    results |= process_page(page_url, repl, stop_line, "labels_subvarieties", print_result=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/en-labels.py", line 91, in process_page
    exec(code, globals())
  File "<string>", line 77
    Wikdiata = "Q854",
           ^
SyntaxError: ':' expected after dictionary key
```

**Comment by BoboTiG** [comment]
Fixed on the Wiktionary: https://en.wiktionary.org/w/index.php?title=Module:labels/data/lang/ta&diff=prev&oldid=81578850
