### ISSUE TITLE
[FR] Fix for keywords-only 'fr-verbe-flexion' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#212]
Commands:
```
$ python -m scripts --locale="fr" --raw --get-word="tange"
$ python -m scripts --locale="fr" --raw --get-word="engrave"
$ python -m scripts --locale="fr" --raw --get-word="dites"
$ python -m scripts --locale="fr" --raw --get-word="perlés"
```

Wikicode:
```
{{fr-verbe-flexion|grp=3|1=dire|imp.p.2p=oui|ind.p.2p=oui|ppfp=oui}}
```

Output:
```
Traceback (most recent call last):
  File "scripts/__main__.py", line 77, in <module>
    sys.exit(main(sys.argv[1:]))
  File "scripts/__main__.py", line 59, in main
    return get.main(args.locale, word=args.get_word, raw=args.raw_output)
  File "scripts/get.py", line 538, in main
    get_and_parse_word(word, locale, raw=raw)
  File "scripts/get.py", line 336, in get_and_parse_word
    details = parse_word(word, code, locale, force=True)
  File "scripts/get.py", line 409, in parse_word
    infinitive = clean(word, t.__str__(), locale)
  File "scripts/utils.py", line 282, in clean
    text = text.replace(tpl, transform(word, tpl[2:-2], locale))
  File "scripts/utils.py", line 348, in transform
    result: str = transform_apply(word, tpl, tuple(parts), locale)
  File "venv/lib/python3.8/site-packages/cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "scripts/utils.py", line 364, in transform_apply
    return eval(templates_multi[locale][tpl])  # type: ignore
  File "<string>", line 1, in <module>
IndexError: list index out of range
```

**Comment by lasconic** [comment]
OK. I guess I will have to move the handling of `fr-verbe-flexion` to `last_template_handler`...
