### ISSUE TITLE
[EN] Fix "en-langs" script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2155]
```python
Traceback (most recent call last):
  File "scripts/en-langs.py", line 89, in <module>
    mres: dict[str, dict[str, str]] = read_all_lines_etym(lines)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/en-langs.py", line 56, in read_all_lines_etym
    exec(concat, globals())
  File "<string>", line 3173, in <module>
NameError: name 'Q4106789' is not defined
```

**Comment by lasconic** [comment]
The last changes on the page are incorrect. I sent a message to the editor. https://en.wiktionary.org/wiki/User_talk:Vininn126#Changes_in_etymology_language_data
