### ISSUE TITLE
Error when latest two snapshots are unavailable

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2260]
I didn't know this issue could happen: the last two Wikimedia dumps are unavailable (both ongoing, or missing).

So, as seen in [this night workflow](https://github.com/BoboTiG/ebook-reader-dict/actions/runs/12111030229): updates are stopped.

Here is the stacktrace:

```python
INFO:wikidict.download:Fetching https://dumps.wikimedia.org/frwiktionary/20241201/frwiktionary-20241201-pages-meta-current.xml.bz2
WARNING:wikidict.download:Wiktionary dump is ongoing ... 
INFO:wikidict.download:Will use the previous one.
INFO:wikidict.download:Fetching https://dumps.wikimedia.org/frwiktionary/20241120/frwiktionary-20241120-pages-meta-current.xml.bz2
Traceback (most recent call last):
  File "wikidict/download.py", line 94, in main
    file = fetch_pages(snapshot, locale, output_dir, callback=callback_progress)
  File "wikidict/download.py", line 71, in fetch_pages
    req.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~^^
  File /.../requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://dumps.wikimedia.org/frwiktionary/20241201/frwiktionary-20241201-pages-meta-current.xml.bz2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "wikidict/__main__.py", line 132, in <module>
    sys.exit(main())
             ~~~~^^
  File "wikidict/__main__.py", line 62, in main
    return download.main(args["LOCALE"])
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "wikidict/download.py", line 102, in main
    file = fetch_pages(snapshot, locale, output_dir, callback=callback_progress)
  File "wikidict/download.py", line 71, in fetch_pages
    req.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~^^
  File /.../requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://dumps.wikimedia.org/frwiktionary/20241120/frwiktionary-20241120-pages-meta-current.xml.bz2
```

**Comment by BoboTiG** [comment]
So it is true, both dups are "in progress" (at the time of writing, so 2024-12-02):
- https://dumps.wikimedia.org/frwiktionary/20241120/
- https://dumps.wikimedia.org/frwiktionary/20241201/

**Comment by BoboTiG** [comment]
In that case, let's try the third snapshot, and then the fourth, and so on until we find a good fit.
