### ISSUE TITLE
[EN] Error with "en-langs.py" script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2265]
Job: https://github.com/BoboTiG/ebook-reader-dict/actions/runs/12267011883/job/34226294474
```python
Traceback (most recent call last):
  File "scripts/en-langs.py", line 89, in <module>
    mres: dict[str, dict[str, str]] = read_all_lines_etym(lines)
                                      ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "scripts/en-langs.py", line 56, in read_all_lines_etym
    exec(concat, globals())
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2
    function u(...)
             ^
SyntaxError: invalid syntax
```

**Comment by lasconic** [comment]
I'll have a look
