### ISSUE TITLE
[FR] Add missing 'latin archaïque' to langs

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#642]
```shell
$ python -m wikidict fr --get-word locus
```
```python
Traceback (most recent call last):
  File "/.../runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.../runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ikidict/__main__.py", line 84, in <module>
    sys.exit(main())
  File "ikidict/__main__.py", line 65, in main
    return get_word.main(args["LOCALE"], args["--get-word"], args["--raw"])
  File "ikidict/get_word.py", line 65, in main
    get_and_parse_word(word, locale, raw)
  File "ikidict/get_word.py", line 17, in get_and_parse_word
    details = parse_word(word, code, locale, force=True)
  File "ikidict/render.py", line 259, in parse_word
    etymology = find_etymology(word, locale, etyl_data[0])
  File "ikidict/render.py", line 162, in find_etymology
    etyl = process_templates(word, clean(etymology), locale)
  File "ikidict/utils.py", line 353, in process_templates
    text = text.replace(tpl, transform(word, tpl[2:-2], locale))
  File "ikidict/utils.py", line 480, in transform
    result: str = transform_apply(word, tpl, tuple(parts), locale)
  File "/.../cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "ikidict/utils.py", line 501, in transform_apply
    return last_template_handler[locale](parts, locale, word=word)
  File "ikidict/lang/fr/__init__.py", line 706, in last_template_handler
    return render_template(template)
  File "ikidict/lang/fr/template_handlers.py", line 738, in render_template
    return template_mapping[tpl](tpl, parts, data)
  File "ikidict/lang/fr/template_handlers.py", line 423, in render_etyl
    phrase = langs[data["1"] or parts.pop(0)]
KeyError: 'latin archaïque'
```

**Comment by lasconic** [comment]
See https://fr.wiktionary.org/wiki/Module:%C3%A9tymologie#L-120
