### ISSUE TITLE
Fix --check-word with subdefinitions

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#685]
```
python -m wikidict fr --check-word cricri
```

causes a crash

**Comment by lasconic** [comment]
See "vache"

**Comment by BoboTiG** [comment]
Here is the error:
```python
Traceback (most recent call last):
  File "/.../python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.../python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 90, in <module>
    sys.exit(main())
  File "__main__.py", line 56, in main
    return check_word.main(args["LOCALE"], args["--check-word"])
  File "check_word.py", line 117, in main
    errors += check(text, subdef, f"{message}.{int_to_roman(subnum).lower()}")
  File "check_word.py", line 21, in check
    clean_text = get_text(html)
  File "check_word.py", line 76, in get_text
    return str(BeautifulSoup(markup=html, features="html.parser").text)
  File "/.../site-packages/bs4/__init__.py", line 342, in __init__
    for (self.markup, self.original_encoding, self.declared_html_encoding,
  File "/.../site-packages/bs4/builder/_htmlparser.py", line 363, in prepare_markup
    dammit = UnicodeDammit(markup, try_encodings, is_html=True,
  File "/.../site-packages/bs4/dammit.py", line 445, in __init__
    for encoding in self.detector.encodings:
  File "/.../site-packages/bs4/dammit.py", line 301, in encodings
    self.declared_encoding = self.find_declared_encoding(
  File "/.../site-packages/bs4/dammit.py", line 378, in find_declared_encoding
    declared_encoding_match = xml_re.search(markup, endpos=xml_endpos)
TypeError: expected string or bytes-like object
```
