### ISSUE TITLE
[EN] Fix support for etyl with a single arg

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#760]
```shell
$ python -m wikidict en --get-word isocheimonal
```
```python
Traceback (most recent call last):
  File "/.../runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.../runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 90, in <module>
    sys.exit(main())
  File "__main__.py", line 66, in main
    return get_word.main(args["LOCALE"], args["--get-word"], args["--raw"])
  File "get_word.py", line 74, in main
    get_and_parse_word(word, locale, raw)
  File "get_word.py", line 36, in get_and_parse_word
    details = get_word(word, locale)
  File "get_word.py", line 17, in get_word
    return parse_word(word, code, locale, force=True)
  File "render.py", line 259, in parse_word
    etymology = find_etymology(word, locale, etyl_data[0])
  File "render.py", line 130, in find_etymology
    etyl = process_templates(word, clean(item), locale)
  File "utils.py", line 416, in process_templates
    text = text.replace(tpl, transform(word, tpl[2:-2], locale))
  File "utils.py", line 558, in transform
    result: str = transform_apply(word, tpl, tuple(parts), locale)
  File "/.../cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "utils.py", line 582, in transform_apply
    return last_template_handler[locale](parts, locale, word=word)
  File "lang/en/__init__.py", line 200, in last_template_handler
    return render_template(template)
  File "lang/en/template_handlers.py", line 1051, in render_template
    return template_mapping[tpl](tpl, parts, data)
  File "lang/en/template_handlers.py", line 262, in render_foreign_derivation
    parts.pop(0)
IndexError: pop from empty list
```

**Comment by BoboTiG** [comment]
Same for `isochimenal` and `isothere`.

**Comment by lasconic** [comment]
crash is caused by 
```
{{etyl|grc}}
```
